window:
  startup_mode: Maximized
  opacity: 0.65

shell:
  program: /usr/bin/zsh
  args:
    - --login
font:
  normal:
    family: JetBrainsMono Nerd Font
    style: Regular

  bold:
    family: JetBrainsMono Nerd Font
    style: Bold

  italic:
    family: JetBrainsMono Nerd Font
    style: Italic

  size: 11

